spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 12345678

mybatis:
  mapper-locations: classpath:mapperXML/*.xml

server:
  port: 8011
